[build]
  publish = "dist"

[settings]
  clean_urls = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/not-found.html"
  status = 404
  force = true
