export const MICROSOFT_CLIENT_ID = process.env.REACT_APP_MICROSOFT_CLIENT_ID;
export const MICROSOFT_TENANT_ID = process.env.REACT_APP_MICROSOFT_TENANT_ID;
export const MICROSOFT_CLIENT_SECRET = process.env.REACT_APP_MICROSOFT_CLIENT_SECRET;
export const BACKEND_BASE_URL = process.env.REACT_APP_BACKEND_BASE_URL;
